import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { AppError } from "../src/errors.js";
import { buildConfigFromFlags, loadConfig } from "../src/config.js";
import { detectBreakingChanges } from "../src/diff.js";
import { generateOutputs } from "../src/generator.js";
import { loadOpenApiDocument } from "../src/openapi.js";
import { validateOpenApiDocument } from "../src/validate.js";

test("loads config, validates OpenAPI, and generates TypeScript output", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));

  try {
    const fixtureSource = path.resolve("examples/petstore.openapi.json");
    const configPath = path.join(tempDir, "typebridge.config.json");

    await writeFile(
      configPath,
      JSON.stringify(
        {
          source: {
            path: fixtureSource,
          },
          outputs: [
            {
              path: "./generated/petstore.ts",
              mode: "types",
            },
          ],
          validation: {
            requireOperationIds: true,
            requireResponseSchemas: true,
          },
        },
        null,
        2,
      ),
      "utf8",
    );

    const { config } = await loadConfig(configPath);
    const loaded = await loadOpenApiDocument(config, configPath);

    validateOpenApiDocument(loaded.document, config);

    const [result] = await generateOutputs({
      config,
      configPath,
      document: loaded.document,
      sourceLabel: loaded.sourceLabel,
    });

    assert.equal(result.changed, true);

    const generatedContent = await readFile(result.outputPath, "utf8");
    assert.match(generatedContent, /This file was generated by TypeBridge\./);
    assert.match(generatedContent, /Output mode: types/);
    assert.match(generatedContent, /export (interface|type) paths/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test("supports flags-first config generation with fetch client output", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));

  try {
    const config = buildConfigFromFlags({
      sourceOverride: {
        path: path.resolve("examples/petstore.openapi.json"),
      },
      outputsOverride: [
        {
          path: "./generated/client.ts",
          mode: "fetch-client",
        },
      ],
    });
    const configPath = path.join(tempDir, "inline.json");
    const loaded = await loadOpenApiDocument(config, configPath, config.source);

    const [result] = await generateOutputs({
      config,
      configPath,
      document: loaded.document,
      sourceLabel: loaded.sourceLabel,
    });

    const generatedContent = await readFile(result.outputPath, "utf8");
    assert.match(generatedContent, /Output mode: fetch-client/);
    assert.match(generatedContent, /export async function listPets/);
    assert.match(generatedContent, /interface TypeBridgeClient/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test("generates react query helpers", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));

  try {
    const config = buildConfigFromFlags({
      sourceOverride: {
        path: path.resolve("examples/petstore.openapi.json"),
      },
      outputsOverride: [
        {
          path: "./generated/react-query.ts",
          mode: "react-query",
        },
      ],
    });
    const configPath = path.join(tempDir, "inline.json");
    const loaded = await loadOpenApiDocument(config, configPath, config.source);

    const [result] = await generateOutputs({
      config,
      configPath,
      document: loaded.document,
      sourceLabel: loaded.sourceLabel,
    });

    const generatedContent = await readFile(result.outputPath, "utf8");
    assert.match(generatedContent, /@tanstack\/react-query/);
    assert.match(generatedContent, /useListPetsQuery/);
    assert.match(generatedContent, /useCreatePetMutation/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test("generates multiple outputs from one config", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));

  try {
    const config = buildConfigFromFlags({
      sourceOverride: {
        path: path.resolve("examples/petstore.openapi.json"),
      },
      outputsOverride: [
        {
          path: "./generated/types.ts",
          mode: "types",
        },
        {
          path: "./generated/client.ts",
          mode: "fetch-client",
        },
      ],
    });
    const configPath = path.join(tempDir, "inline.json");
    const loaded = await loadOpenApiDocument(config, configPath, config.source);

    const results = await generateOutputs({
      config,
      configPath,
      document: loaded.document,
      sourceLabel: loaded.sourceLabel,
    });

    assert.equal(results.length, 2);
    assert.equal(results.every((result) => result.changed), true);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test("reports config validation failures with actionable messages", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));

  try {
    const configPath = path.join(tempDir, "broken.config.json");
    await writeFile(
      configPath,
      JSON.stringify(
        {
          source: {},
          outputs: [
            {
              path: "./generated/out.ts",
              mode: "unknown",
            },
          ],
        },
        null,
        2,
      ),
      "utf8",
    );

    await assert.rejects(
      () => loadConfig(configPath),
      (error: unknown) =>
        error instanceof AppError &&
        error.message.includes("`source` must define either `path` or `url`.") &&
        error.message.includes("`outputs[0].mode` must be one of: types, fetch-client, react-query."),
    );
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test("reports OpenAPI validation failures for missing operation ids and schemas", () => {
  const invalidDocument = {
    openapi: "3.0.3",
    info: {
      title: "Broken API",
      version: "1.0.0",
    },
    paths: {
      "/broken": {
        get: {
          responses: {
            "200": {
              description: "ok",
            },
          },
        },
      },
    },
  };

  assert.throws(
    () =>
      validateOpenApiDocument(invalidDocument, {
        source: {
          path: "./broken.json",
        },
        outputs: [
          {
            path: "./generated/out.ts",
            mode: "types",
          },
        ],
        validation: {
          requireOperationIds: true,
          requireResponseSchemas: true,
        },
      }),
    (error: unknown) =>
      error instanceof AppError &&
      error.message.includes("GET /broken is missing an operationId.") &&
      error.message.includes("GET /broken response 200 is missing a content schema."),
  );
});

test("loads a remote OpenAPI document and builds a remote watch plan", async () => {
  const originalFetch = globalThis.fetch;
  try {
    const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));
    const configPath = path.join(tempDir, "remote.config.json");

    try {
      globalThis.fetch = async () =>
        new Response(JSON.stringify(sampleDocument("Remote API")), {
          status: 200,
          headers: {
            "content-type": "application/json",
          },
        });

      const config = {
        source: {
          url: "https://example.test/openapi.json",
        },
        outputs: [
          {
            path: "./generated/remote.ts",
            mode: "types" as const,
          },
        ],
        watch: {
          pollIntervalMs: 1234,
          retryDelayMs: 567,
        },
      };

      const loaded = await loadOpenApiDocument(config, configPath);
      assert.equal(loaded.sourceLabel, config.source.url);
      assert.equal(loaded.watchPlan.remote?.pollIntervalMs, 1234);
      assert.equal(loaded.watchPlan.remote?.retryDelayMs, 567);
      assert.deepEqual(loaded.watchPlan.localFiles, [configPath]);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("tracks local external refs so watch mode can observe multi-file schemas", async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "typebridge-"));

  try {
    const schemaDir = path.join(tempDir, "schema");
    await mkdir(schemaDir, { recursive: true });

    const configPath = path.join(tempDir, "typebridge.config.json");
    const rootPath = path.join(schemaDir, "root.json");
    const componentPath = path.join(schemaDir, "components.json");

    await writeFile(
      componentPath,
      JSON.stringify({
        components: {
          schemas: {
            Todo: {
              type: "object",
              required: ["id", "title"],
              properties: {
                id: { type: "string" },
                title: { type: "string" },
              },
            },
          },
        },
      }),
      "utf8",
    );

    await writeFile(
      rootPath,
      JSON.stringify({
        openapi: "3.0.3",
        info: {
          title: "Multi-file API",
          version: "1.0.0",
        },
        paths: {
          "/todos": {
            get: {
              operationId: "listTodos",
              responses: {
                "200": {
                  description: "ok",
                  content: {
                    "application/json": {
                      schema: {
                        type: "array",
                        items: {
                          "$ref": "./components.json#/components/schemas/Todo",
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      }),
      "utf8",
    );

    await writeFile(
      configPath,
      JSON.stringify({
        source: {
          path: "./schema/root.json",
        },
        outputs: [
          {
            path: "./generated/todos.ts",
            mode: "types",
          },
        ],
      }),
      "utf8",
    );

    const { config } = await loadConfig(configPath);
    const loaded = await loadOpenApiDocument(config, configPath);

    assert.equal(loaded.watchPlan.localFiles.includes(configPath), true);
    assert.equal(loaded.watchPlan.localFiles.includes(rootPath), true);
    assert.equal(loaded.watchPlan.localFiles.includes(componentPath), true);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test("detects breaking changes across contracts", () => {
  const previousDocument = {
    openapi: "3.0.3",
    info: {
      title: "Previous",
      version: "1.0.0",
    },
    paths: {
      "/pets": {
        get: {
          operationId: "listPets",
          parameters: [
            {
              name: "limit",
              in: "query",
              required: false,
              schema: {
                type: "integer",
              },
            },
          ],
          responses: {
            "200": {
              description: "ok",
              content: {
                "application/json": {
                  schema: {
                    $ref: "#/components/schemas/PetList",
                  },
                },
              },
            },
          },
          requestBody: {
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/PetFilter",
                },
              },
            },
          },
        },
      },
    },
    components: {
      schemas: {
        PetList: {
          type: "object",
          required: ["items"],
          properties: {
            items: {
              type: "array",
              items: {
                $ref: "#/components/schemas/Pet",
              },
            },
            nextCursor: {
              type: "string",
              enum: ["a", "b"],
            },
          },
        },
        PetFilter: {
          type: "object",
          properties: {
            tag: {
              type: "string",
            },
          },
        },
        Pet: {
          type: "object",
          properties: {
            id: {
              type: "string",
            },
            name: {
              type: "string",
            },
          },
        },
      },
    },
  };

  const nextDocument = {
    openapi: "3.0.3",
    info: {
      title: "Next",
      version: "2.0.0",
    },
    paths: {
      "/pets": {
        get: {
          operationId: "listPets",
          parameters: [
            {
              name: "limit",
              in: "query",
              required: true,
              schema: {
                type: "integer",
              },
            },
          ],
          responses: {
            "200": {
              description: "ok",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                  },
                },
              },
            },
          },
          requestBody: {
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["tag"],
                  properties: {
                    tag: {
                      type: "string",
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    components: {
      schemas: {
        PetList: {
          type: "object",
          required: ["items"],
          properties: {
            items: {
              type: "array",
              items: {
                $ref: "#/components/schemas/Pet",
              },
            },
            nextCursor: {
              type: "string",
              enum: ["a"],
            },
          },
        },
        Pet: {
          type: "object",
          properties: {
            id: {
              type: "string",
            },
          },
        },
      },
    },
  };

  const issues = detectBreakingChanges(previousDocument, nextDocument);
  const codes = issues.map((issue) => issue.code);

  assert.ok(codes.includes("request-parameter-became-required"));
  assert.ok(codes.includes("request-field-became-required"));
  assert.ok(codes.includes("removed-enum-value"));
  assert.ok(codes.includes("incompatible-schema-type"));
  assert.ok(codes.includes("response-field-removed"));
});

function sampleDocument(title: string) {
  return {
    openapi: "3.0.3",
    info: {
      title,
      version: "1.0.0",
    },
    paths: {
      "/todos": {
        get: {
          operationId: "listTodos",
          responses: {
            "200": {
              description: "ok",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["id", "title"],
                      properties: {
                        id: { type: "string" },
                        title: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  };
}
