import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import openapiTS, { astToString } from "openapi-typescript";

import { getOperations } from "./oas.js";
import type { GenerateResult, OutputConfig, TypeBridgeConfig } from "./types.js";
import { quote, toCamelCase, toPascalCase } from "./utils.js";

export async function generateOutputs(args: {
  config: TypeBridgeConfig;
  configPath: string;
  document: Record<string, unknown>;
  sourceLabel: string;
  check?: boolean;
}): Promise<GenerateResult[]> {
  const results: GenerateResult[] = [];
  const typeSource = await buildTypeSource(args.document);

  for (const output of args.config.outputs) {
    const absoluteOutputPath = path.resolve(path.dirname(args.configPath), output.path);
    const content = renderOutput(output, typeSource, args.document, args.sourceLabel);
    const changed = await writeIfNeeded(absoluteOutputPath, content, args.check ?? false);

    results.push({
      outputPath: absoluteOutputPath,
      changed,
      mode: output.mode,
    });
  }

  return results;
}

async function buildTypeSource(document: Record<string, unknown>): Promise<string> {
  const ast = await openapiTS(document as unknown as Parameters<typeof openapiTS>[0], {
    alphabetize: true,
    exportType: true,
    enum: true,
  });

  return astToString(ast).trim();
}

function renderOutput(
  output: OutputConfig,
  typeSource: string,
  document: Record<string, unknown>,
  sourceLabel: string,
): string {
  switch (output.mode) {
    case "types":
      return withBanner(typeSource, sourceLabel, output.mode);
    case "fetch-client":
      return withBanner(renderFetchClient(typeSource, document), sourceLabel, output.mode);
    case "react-query":
      return withBanner(renderReactQueryClient(typeSource, document), sourceLabel, output.mode);
  }
}

function withBanner(content: string, sourceLabel: string, mode: OutputConfig["mode"]): string {
  const banner = [
    "/**",
    " * This file was generated by TypeBridge.",
    ` * Source: ${sourceLabel}`,
    ` * Output mode: ${mode}`,
    " * Do not edit this file directly.",
    " */",
    "",
  ].join("\n");

  return `${banner}${content}`.trimEnd() + "\n";
}

function renderFetchClient(typeSource: string, document: Record<string, unknown>): string {
  const operations = getOperations(document);
  const functions = operations
    .map((operation) => {
      const functionName = toCamelCase(operation.operationId);
      return [
        `export async function ${functionName}(client: TypeBridgeClient, args: RequestArgs<${quote(operation.operationId)}> = {}): Promise<SuccessResponse<${quote(operation.operationId)}>> {`,
        `  return request(client, ${quote(operation.method.toUpperCase())}, ${quote(operation.route)}, args);`,
        `}`,
      ].join("\n");
    })
    .join("\n\n");

  return `${typeSource}

${renderRuntimeHelpers()}

${functions}
`;
}

function renderReactQueryClient(typeSource: string, document: Record<string, unknown>): string {
  const operations = getOperations(document);
  const lines: string[] = [
    typeSource,
    "",
    'import { queryOptions, useMutation, useQuery, type UseMutationOptions, type UseQueryOptions } from "@tanstack/react-query";',
    "",
    renderRuntimeHelpers(),
    "",
  ];

  for (const operation of operations) {
    const functionName = toCamelCase(operation.operationId);
    const hookName = `use${toPascalCase(operation.operationId)}`;
    const queryKeyName = `${functionName}QueryKey`;
    const requestFnName = `${functionName}Request`;
    const requestLine = [
      `export async function ${requestFnName}(client: TypeBridgeClient, args: RequestArgs<${quote(operation.operationId)}> = {}): Promise<SuccessResponse<${quote(operation.operationId)}>> {`,
      `  return request(client, ${quote(operation.method.toUpperCase())}, ${quote(operation.route)}, args);`,
      `}`,
    ].join("\n");

    lines.push(requestLine, "");

    if (operation.method === "get" || operation.method === "head") {
      lines.push(
        `export const ${queryKeyName} = (args: RequestArgs<${quote(operation.operationId)}> = {}) => [${quote(
          functionName,
        )}, stableValue(args.path), stableValue(args.query), stableValue(args.body)] as const;`,
        "",
        `export function ${functionName}QueryOptions(client: TypeBridgeClient, args: RequestArgs<${quote(
          operation.operationId,
        )}> = {}, options: Omit<UseQueryOptions<SuccessResponse<${quote(
          operation.operationId,
        )}>, Error>, "queryKey" | "queryFn"> = {}) {`,
        `  return queryOptions({`,
        `    queryKey: ${queryKeyName}(args),`,
        `    queryFn: () => ${requestFnName}(client, args),`,
        `    ...options,`,
        `  });`,
        `}`,
        "",
        `export function ${hookName}Query(client: TypeBridgeClient, args: RequestArgs<${quote(
          operation.operationId,
        )}> = {}, options: Omit<UseQueryOptions<SuccessResponse<${quote(
          operation.operationId,
        )}>, Error>, "queryKey" | "queryFn"> = {}) {`,
        `  return useQuery(${functionName}QueryOptions(client, args, options));`,
        `}`,
        "",
      );
    } else {
      lines.push(
        `export function ${hookName}Mutation(client: TypeBridgeClient, options: UseMutationOptions<SuccessResponse<${quote(
          operation.operationId,
        )}>, Error, RequestArgs<${quote(operation.operationId)}>> = {}) {`,
        `  return useMutation({`,
        `    mutationFn: (args: RequestArgs<${quote(operation.operationId)}>) => ${requestFnName}(client, args),`,
        `    ...options,`,
        `  });`,
        `}`,
        "",
      );
    }
  }

  return lines.join("\n").trim();
}

function renderRuntimeHelpers(): string {
  return `
export interface TypeBridgeClient {
  baseUrl?: string;
  fetch?: typeof fetch;
  headers?: HeadersInit;
}

type OperationId = keyof operations;
type OperationById<Id extends OperationId> = operations[Id];
type ParametersOf<T> = T extends { parameters: infer Parameters } ? Parameters : never;
type MaybeValue<T> = [T] extends [never] ? undefined : T;
type PathParams<T> = ParametersOf<T> extends { path?: infer Path } ? Path : never;
type QueryParams<T> = ParametersOf<T> extends { query?: infer Query } ? Query : never;
type HeaderParams<T> = ParametersOf<T> extends { header?: infer Header } ? Header : never;
type CookieParams<T> = ParametersOf<T> extends { cookie?: infer Cookie } ? Cookie : never;
type RequestBodyContent<T> = T extends { requestBody?: { content: infer Content } }
  ? Content
  : T extends { requestBody: { content: infer Content } }
    ? Content
    : never;
type RequestBody<T> = RequestBodyContent<T> extends never
  ? never
  : "application/json" extends keyof RequestBodyContent<T>
    ? RequestBodyContent<T>["application/json"]
    : RequestBodyContent<T>[keyof RequestBodyContent<T>];
type ResponseContent<T> = T extends { content: infer Content }
  ? "application/json" extends keyof Content
    ? Content["application/json"]
    : Content[keyof Content]
  : void;
type SuccessResponse<T extends OperationId> = OperationById<T> extends { responses: infer Responses }
  ? {
      [Key in keyof Responses]: Key extends 200 | 201 | 202 | 203 | 204 | 205 | 206
        ? ResponseContent<Responses[Key]>
        : Key extends \`2\${number}\${number}\`
          ? ResponseContent<Responses[Key]>
          : never;
    }[keyof Responses]
  : never;

export type RequestArgs<Id extends OperationId> = {
  path?: MaybeValue<PathParams<OperationById<Id>>>;
  query?: MaybeValue<QueryParams<OperationById<Id>>>;
  header?: MaybeValue<HeaderParams<OperationById<Id>>>;
  cookie?: MaybeValue<CookieParams<OperationById<Id>>>;
  body?: MaybeValue<RequestBody<OperationById<Id>>>;
  init?: Omit<RequestInit, "method" | "headers" | "body">;
};

function stableValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => stableValue(item));
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, item]) => [key, stableValue(item)]),
    );
  }

  return value;
}

function buildUrl(route: string, args: RequestArgs<OperationId>): string {
  const pathParams = (args.path ?? {}) as Record<string, unknown>;
  const queryParams = (args.query ?? {}) as Record<string, unknown>;
  const url = route.replace(/\\{([^}]+)\\}/g, (_, segment: string) => {
    const value = pathParams[segment];

    if (value === undefined || value === null) {
      throw new Error(\`Missing path parameter: \${segment}\`);
    }

    return encodeURIComponent(String(value));
  });
  const search = new URLSearchParams();

  for (const [key, value] of Object.entries(queryParams)) {
    if (value === undefined || value === null) {
      continue;
    }

    if (Array.isArray(value)) {
      for (const item of value) {
        search.append(key, String(item));
      }
      continue;
    }

    search.set(key, String(value));
  }

  const query = search.toString();
  return query ? \`\${url}?\${query}\` : url;
}

async function request<Id extends OperationId>(
  client: TypeBridgeClient,
  method: string,
  route: string,
  args: RequestArgs<Id>,
): Promise<SuccessResponse<Id>> {
  const fetchImpl = client.fetch ?? fetch;
  const baseUrl = client.baseUrl?.replace(/\\/$/, "") ?? "";
  const url = \`\${baseUrl}\${buildUrl(route, args as unknown as RequestArgs<OperationId>)}\`;
  const headers = new Headers(client.headers ?? {});
  const extraHeaders = args.header as Record<string, string> | undefined;

  if (extraHeaders) {
    for (const [key, value] of Object.entries(extraHeaders)) {
      if (value !== undefined) {
        headers.set(key, String(value));
      }
    }
  }

  const requestInit: RequestInit = {
    ...(args.init ?? {}),
    method,
    headers,
  };

  if (args.body !== undefined) {
    if (!headers.has("content-type")) {
      headers.set("content-type", "application/json");
    }

    requestInit.body = JSON.stringify(args.body);
  }

  const response = await fetchImpl(url, requestInit);

  if (!response.ok) {
    throw new Error(\`Request failed with status \${response.status} for \${method} \${route}\`);
  }

  if (response.status === 204 || response.status === 205) {
    return undefined as SuccessResponse<Id>;
  }

  return (await response.json()) as SuccessResponse<Id>;
}
`.trim();
}

async function writeIfNeeded(
  outputPath: string,
  nextContent: string,
  check: boolean,
): Promise<boolean> {
  let currentContent: string | null = null;

  try {
    currentContent = await readFile(outputPath, "utf8");
  } catch {
    currentContent = null;
  }

  const changed = currentContent !== nextContent;

  if (!check && changed) {
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, nextContent, "utf8");
  }

  return changed;
}
